### ISSUE TITLE
Tell David to get off Github

### ISSUE THREAD

**Issue by shanselman** [davidfowl/uController#3] opened 2017-09-01 08:06 UTC

**Comment by Drawaes** [comment] 2017-09-01 08:18
I don't know. In the first two weeks the baby wants to be close to it's parents but that can be cuddling dad while he codes. If the dad is doing the right thing and taking large amounts of night shifts to allow the mother to get sleep to recover

``` csharp
if (wife.Sleeping && baby.Sleeping && baby.Location == Location.LyingOnDad && laptop.Distance < arm.Length)
{
        laptop.Brightness = 0.000001;
        DO
        {
               //What you find fun on the computer
         } while (everyoneElseAsleep)
}
```

**Comment by davidfowl** [comment] 2017-09-03 09:02
Closing as by design

**Closed as completed by davidfowl** 2017-09-03 09:02 UTC
